/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: afXULSfGYmou2jFpEc2QWJ
// Component: JQeoqLZhfAOP

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TextInput from "../../TextInput"; // plasmic-import: SePhlRlvEn3n/component
import Button from "../../Button"; // plasmic-import: oVzoHzMf1TLl/component
import { SideEffect } from "@plasmicpkgs/plasmic-basic-components";
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: afXULSfGYmou2jFpEc2QWJ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: afXULSfGYmou2jFpEc2QWJ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: afXULSfGYmou2jFpEc2QWJ/projectcss
import sty from "./PlasmicCharge.module.css"; // plasmic-import: JQeoqLZhfAOP/css

import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: eeiQdsLura6L/icon
import SearchSvgIcon from "./icons/PlasmicIcon__SearchSvg"; // plasmic-import: fjupp6w2fUeo/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: VZ6Vl-sB0jLM/icon
import ChevronRightIcon from "../fragment_icons/icons/PlasmicIcon__ChevronRight"; // plasmic-import: GHdF3hS-oP_3/icon
import ChevronLeftIcon from "../fragment_icons/icons/PlasmicIcon__ChevronLeft"; // plasmic-import: r9Upp9NbiZkf/icon
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: mHP_U4hM0IP3/icon
import VisamasterSvgIcon from "./icons/PlasmicIcon__VisamasterSvg"; // plasmic-import: MnaaH4eG1eMW/icon

createPlasmicElementProxy;

export type PlasmicCharge__VariantMembers = {};
export type PlasmicCharge__VariantsArgs = {};
type VariantPropType = keyof PlasmicCharge__VariantsArgs;
export const PlasmicCharge__VariantProps = new Array<VariantPropType>();

export type PlasmicCharge__ArgsType = {};
type ArgPropType = keyof PlasmicCharge__ArgsType;
export const PlasmicCharge__ArgProps = new Array<ArgPropType>();

export type PlasmicCharge__OverridesType = {
  root?: Flex__<"div">;
  txtAmount?: Flex__<typeof TextInput>;
  sideeffectPageload?: Flex__<typeof SideEffect>;
  onLoad?: Flex__<typeof SideEffect>;
  embedHtml?: Flex__<typeof Embed>;
};

export interface DefaultChargeProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCharge__RenderFunc(props: {
  variants: PlasmicCharge__VariantsArgs;
  args: PlasmicCharge__ArgsType;
  overrides: PlasmicCharge__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "waiting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "txtAmount.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          hasVariant(globalVariants, "screen", "mobileOnly")
            ? (() => {
                try {
                  return $ctx.query.amount / 10;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()
            : (() => {
                try {
                  return $ctx.query.amount / 10;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()
      },
      {
        path: "user",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => ({})
      },
      {
        path: "iplocation",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "paymentFactor",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => ({})
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicCharge.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicCharge.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicCharge.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          {(
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? (() => {
                  try {
                    return (
                      $ctx.query.type == "charge" ||
                      $ctx.query.type == "payment-error" ||
                      $ctx.query.type == "" ||
                      $ctx.query.type.length == 0
                    );
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return true;
                    }
                    throw e;
                  }
                })()
              : (() => {
                  try {
                    return (
                      $ctx.query.type == "charge" ||
                      $ctx.query.type == "payment-error" ||
                      $ctx.query.type == "" ||
                      $ctx.query.type.length == 0
                    );
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return true;
                    }
                    throw e;
                  }
                })()
          ) ? (
            <section className={classNames(projectcss.all, sty.section__el71G)}>
              <div className={classNames(projectcss.all, sty.freeBox___4W513)}>
                <div className={classNames(projectcss.all, sty.freeBox__zpczd)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__s7A3I)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "30px"
                        : "30px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "30px"
                        : "30px"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/katibe/images/image42.svg",
                      fullWidth: 102.473,
                      fullHeight: 108.85,
                      aspectRatio: 0.941415
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tt10U
                    )}
                  >
                    {"\u067e\u0630\u06cc\u0631\u063424"}
                  </div>
                  {(() => {
                    try {
                      return $state.waiting;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return true;
                      }
                      throw e;
                    }
                  })() ? (
                    <Icon2Icon
                      className={classNames(projectcss.all, sty.svg__ywAn8)}
                      role={"img"}
                    />
                  ) : null}
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__e545Y)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mgza5)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___8Qwum
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hdkXn
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return (
                                "شارژ کیف پول " +
                                (
                                  $state.user.users[0].name +
                                  " " +
                                  $state.user.users[0].family
                                ).replaceAll("null", "")
                              );
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "\u0634\u0627\u0631\u0698 \u06a9\u06cc\u0641 \u067e\u0648\u0644";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                    {(() => {
                      try {
                        return $ctx.query.type == "payment-error";
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return true;
                        }
                        throw e;
                      }
                    })() ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__f1XqE
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gSthV
                          )}
                        >
                          {
                            "\u062e\u0637\u0627 \u062f\u0631 \u067e\u0631\u062f\u0627\u062e\u062a. \u0644\u0637\u0641\u0627 \u062f\u0648\u0628\u0627\u0631\u0647 \u062a\u0644\u0627\u0634 \u06a9\u0646\u06cc\u062f."
                          }
                        </div>
                      </div>
                    ) : null}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__qSd5)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___8DxW)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bu3Bj)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__q0X5N
                        )}
                      >
                        {"\u0645\u0628\u0644\u063a:"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___77Tb1
                      )}
                    >
                      {(() => {
                        const child$Props = {
                          className: classNames(
                            "__wab_instance",
                            sty.txtAmount
                          ),
                          onChange: async (...eventArgs: any) => {
                            ((...eventArgs) => {
                              generateStateOnChangeProp($state, [
                                "txtAmount",
                                "value"
                              ])((e => e.target?.value).apply(null, eventArgs));
                            }).apply(null, eventArgs);

                            if (
                              eventArgs.length > 1 &&
                              eventArgs[1] &&
                              eventArgs[1]._plasmic_state_init_
                            ) {
                              return;
                            }
                          },
                          placeholder: "0",
                          type: "number",
                          value:
                            generateStateValueProp($state, [
                              "txtAmount",
                              "value"
                            ]) ?? ""
                        };

                        initializePlasmicStates(
                          $state,
                          [
                            {
                              name: "txtAmount.value",
                              initFunc: ({ $props, $state, $queries }) =>
                                hasVariant(
                                  globalVariants,
                                  "screen",
                                  "mobileOnly"
                                )
                                  ? (() => {
                                      try {
                                        return $ctx.query.amount / 10;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return undefined;
                                        }
                                        throw e;
                                      }
                                    })()
                                  : (() => {
                                      try {
                                        return $ctx.query.amount / 10;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return undefined;
                                        }
                                        throw e;
                                      }
                                    })()
                            }
                          ],
                          []
                        );
                        return (
                          <TextInput
                            data-plasmic-name={"txtAmount"}
                            data-plasmic-override={overrides.txtAmount}
                            {...child$Props}
                          />
                        );
                      })()}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___04YF
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                          <React.Fragment>
                            {(() => {
                              try {
                                return (() => {
                                  function numberToPersianWords(num) {
                                    if (
                                      num == "" ||
                                      num == 0 ||
                                      num == "0" ||
                                      num == "NaN"
                                    ) {
                                      return "صفر";
                                    }
                                    const yekan = [
                                      "",
                                      "یک",
                                      "دو",
                                      "سه",
                                      "چهار",
                                      "پنج",
                                      "شش",
                                      "هفت",
                                      "هشت",
                                      "نه"
                                    ];

                                    const dahgan = [
                                      "",
                                      "ده",
                                      "بیست",
                                      "سی",
                                      "چهل",
                                      "پنجاه",
                                      "شصت",
                                      "هفتاد",
                                      "هشتاد",
                                      "نود"
                                    ];

                                    const sadgan = [
                                      "",
                                      "صد",
                                      "دویست",
                                      "سیصد",
                                      "چهارصد",
                                      "پانصد",
                                      "ششصد",
                                      "هفتصد",
                                      "هشتصد",
                                      "نهصد"
                                    ];

                                    const dah = [
                                      "ده",
                                      "یازده",
                                      "دوازده",
                                      "سیزده",
                                      "چهارده",
                                      "پانزده",
                                      "شانزده",
                                      "هفده",
                                      "هجده",
                                      "نوزده"
                                    ];

                                    const parts = [
                                      "",
                                      "هزار",
                                      "میلیون",
                                      "میلیارد",
                                      "تریلیون"
                                    ];

                                    if (num === 0) return "صفر";
                                    num = Math.floor(num);
                                    const groups = [];
                                    while (num > 0) {
                                      groups.push(num % 1000);
                                      num = Math.floor(num / 1000);
                                    }
                                    const convertThreeDigits = n => {
                                      let words = [];
                                      let s = Math.floor(n / 100);
                                      let d = Math.floor((n % 100) / 10);
                                      let y = n % 10;
                                      if (s > 0) words.push(sadgan[s]);
                                      if (d === 1 && y > 0) {
                                        words.push(dah[y]);
                                      } else {
                                        if (d > 0) words.push(dahgan[d]);
                                        if (y > 0) words.push(yekan[y]);
                                      }
                                      return words.join(" و ");
                                    };
                                    const result = [];
                                    for (let i = 0; i < groups.length; i++) {
                                      if (groups[i] !== 0) {
                                        let words = convertThreeDigits(
                                          groups[i]
                                        );
                                        if (parts[i]) {
                                          words += " " + parts[i];
                                        }
                                        result.unshift(words);
                                      }
                                    }
                                    return result.join(" و ");
                                  }
                                  return (
                                    numberToPersianWords(
                                      $state.txtAmount.value
                                    ) + " تومان"
                                  );
                                })();
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "\u0631\u06cc\u0627\u0644";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        ) : (
                          <React.Fragment>
                            {(() => {
                              try {
                                return (() => {
                                  function numberToPersianWords(num) {
                                    if (
                                      num == "" ||
                                      num == 0 ||
                                      num == "0" ||
                                      num == "NaN"
                                    ) {
                                      return "صفر";
                                    }
                                    const yekan = [
                                      "",
                                      "یک",
                                      "دو",
                                      "سه",
                                      "چهار",
                                      "پنج",
                                      "شش",
                                      "هفت",
                                      "هشت",
                                      "نه"
                                    ];

                                    const dahgan = [
                                      "",
                                      "ده",
                                      "بیست",
                                      "سی",
                                      "چهل",
                                      "پنجاه",
                                      "شصت",
                                      "هفتاد",
                                      "هشتاد",
                                      "نود"
                                    ];

                                    const sadgan = [
                                      "",
                                      "صد",
                                      "دویست",
                                      "سیصد",
                                      "چهارصد",
                                      "پانصد",
                                      "ششصد",
                                      "هفتصد",
                                      "هشتصد",
                                      "نهصد"
                                    ];

                                    const dah = [
                                      "ده",
                                      "یازده",
                                      "دوازده",
                                      "سیزده",
                                      "چهارده",
                                      "پانزده",
                                      "شانزده",
                                      "هفده",
                                      "هجده",
                                      "نوزده"
                                    ];

                                    const parts = [
                                      "",
                                      "هزار",
                                      "میلیون",
                                      "میلیارد",
                                      "تریلیون"
                                    ];

                                    if (num === 0) return "صفر";
                                    num = Math.floor(num);
                                    const groups = [];
                                    while (num > 0) {
                                      groups.push(num % 1000);
                                      num = Math.floor(num / 1000);
                                    }
                                    const convertThreeDigits = n => {
                                      let words = [];
                                      let s = Math.floor(n / 100);
                                      let d = Math.floor((n % 100) / 10);
                                      let y = n % 10;
                                      if (s > 0) words.push(sadgan[s]);
                                      if (d === 1 && y > 0) {
                                        words.push(dah[y]);
                                      } else {
                                        if (d > 0) words.push(dahgan[d]);
                                        if (y > 0) words.push(yekan[y]);
                                      }
                                      return words.join(" و ");
                                    };
                                    const result = [];
                                    for (let i = 0; i < groups.length; i++) {
                                      if (groups[i] !== 0) {
                                        let words = convertThreeDigits(
                                          groups[i]
                                        );
                                        if (parts[i]) {
                                          words += " " + parts[i];
                                        }
                                        result.unshift(words);
                                      }
                                    }
                                    return result.join(" و ");
                                  }
                                  return (
                                    numberToPersianWords(
                                      $state.txtAmount.value
                                    ) + " تومان"
                                  );
                                })();
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "\u0631\u06cc\u0627\u0644";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__u3FHn)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__om7Cg)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__eTbjJ)}
                    >
                      {(() => {
                        try {
                          return (
                            $state.iplocation &&
                            $state.iplocation != "" &&
                            $state.iplocation.toLowerCase().trim() !== "iran"
                          );
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__b13Ug
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>
                              {
                                "\u0644\u0637\u0641\u0627 \u0645\u0637\u0645\u0626\u0646 \u0634\u0648\u06cc\u062f \u06a9\u0647 "
                              }
                            </React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#FF0000" }}
                            >
                              {
                                "VPN/\u0641\u06cc\u0644\u062a\u0631\u0634\u06a9\u0646"
                              }
                            </span>
                            <React.Fragment>
                              {
                                " \u0634\u0645\u0627 \u062e\u0627\u0645\u0648\u0634 \u0627\u0633\u062a \u0648 \u0633\u067e\u0633 \u062f\u06a9\u0645\u0647 \u067e\u0631\u062f\u0627\u062e\u062a \u0631\u0627 \u0628\u0632\u0646\u06cc\u062f."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      ) : null}
                      <Button
                        children2={"\u067e\u0631\u062f\u0627\u062e\u062a"}
                        className={classNames(
                          "__wab_instance",
                          sty.button__gCvRa
                        )}
                        onClick={async event => {
                          const $steps = {};

                          $steps["updateWaiting"] = false
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["waiting"]
                                  },
                                  operation: 0,
                                  value: true
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateWaiting"] != null &&
                            typeof $steps["updateWaiting"] === "object" &&
                            typeof $steps["updateWaiting"].then === "function"
                          ) {
                            $steps["updateWaiting"] =
                              await $steps["updateWaiting"];
                          }

                          $steps["updateWaiting3"] = true
                            ? (() => {
                                const actionArgs = {
                                  args: [
                                    (() => {
                                      try {
                                        return (
                                          "http://apigw.paziresh24.com/katibe/v1/payment/p24/" +
                                          $ctx.query.userid +
                                          "/" +
                                          $state.txtAmount.value * 10 +
                                          "/?time=" +
                                          new Date().toISOString()
                                        );
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return undefined;
                                        }
                                        throw e;
                                      }
                                    })()
                                  ]
                                };
                                return $globalActions[
                                  "Hamdast.openLink"
                                ]?.apply(null, [...actionArgs.args]);
                              })()
                            : undefined;
                          if (
                            $steps["updateWaiting3"] != null &&
                            typeof $steps["updateWaiting3"] === "object" &&
                            typeof $steps["updateWaiting3"].then === "function"
                          ) {
                            $steps["updateWaiting3"] =
                              await $steps["updateWaiting3"];
                          }
                        }}
                        size={"compact"}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? (() => {
                  try {
                    return $ctx.query.type == "payment-success";
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return true;
                    }
                    throw e;
                  }
                })()
              : (() => {
                  try {
                    return $ctx.query.type == "payment-success";
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return true;
                    }
                    throw e;
                  }
                })()
          ) ? (
            <section className={classNames(projectcss.all, sty.section__wJDgg)}>
              <div className={classNames(projectcss.all, sty.freeBox__qq8I)}>
                <div className={classNames(projectcss.all, sty.freeBox__zWeDv)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__sK1Hf)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "30px"
                        : "30px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "30px"
                        : "30px"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/katibe/images/image42.svg",
                      fullWidth: 102.473,
                      fullHeight: 108.85,
                      aspectRatio: 0.941415
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__c0Lxz
                    )}
                  >
                    {"\u067e\u0630\u06cc\u0631\u063424"}
                  </div>
                  {(() => {
                    try {
                      return $state.waiting;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return true;
                      }
                      throw e;
                    }
                  })() ? (
                    <Icon2Icon
                      className={classNames(projectcss.all, sty.svg__zq7QO)}
                      role={"img"}
                    />
                  ) : null}
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__csl4K)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___3YjQ2)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__htNqZ)}
                    >
                      <Icon14Icon
                        className={classNames(projectcss.all, sty.svg__cySms)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xU50
                        )}
                      >
                        {
                          "\u067e\u0631\u062f\u0627\u062e\u062a \u0628\u0627 \u0645\u0648\u0641\u0642\u06cc\u062a \u0627\u0646\u062c\u0627\u0645 \u0634\u062f."
                        }
                      </div>
                    </div>
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? (() => {
                            try {
                              return $state.user.users[0].name ||
                                $state.user.users[0].family
                                ? true
                                : false;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return false;
                              }
                              throw e;
                            }
                          })()
                        : (() => {
                            try {
                              return true;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return true;
                              }
                              throw e;
                            }
                          })()
                    ) ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ticJa
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dYzuo
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.user.users[0].name ||
                                  $state.user.users[0].family
                                  ? "لطفا به " +
                                      $state.user.users[0].name +
                                      " " +
                                      $state.user.users[0].family +
                                      " اطلاع دهید تا نوبت‌ش را نهایی کند."
                                  : "لطفا به کاربر مورد نظر اطلاع دهید تا نوبت‌ش را نهایی کند.";
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return " ";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                    ) : null}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__kR2Ra)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jDaK0)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fOzUo)}
                    >
                      <Button
                        children2={
                          "\u0627\u0631\u0633\u0627\u0644 \u0631\u0633\u06cc\u062f \u067e\u0631\u062f\u0627\u062e\u062a"
                        }
                        className={classNames(
                          "__wab_instance",
                          sty.button___0EZ9F
                        )}
                        onClick={async event => {
                          const $steps = {};

                          $steps["runCode"] = true
                            ? (() => {
                                const actionArgs = {
                                  customFunction: async () => {
                                    return (() => {
                                      const shareData = {
                                        title:
                                          "پرداخت موفق به مبلغ " +
                                          $ctx.query.amount / 10 +
                                          " تومان",
                                        text: "پرداخت با موفقیت انجام شد. لطفا نوبت خود را نهایی کنید.",
                                        url:
                                          "https://katibe.paziresh24.com/charge/?userid=" +
                                          $ctx.query.userid +
                                          "&amount=" +
                                          $ctx.query.amount +
                                          "&type=payment-success&factorid=" +
                                          $ctx.query.factorid
                                      };
                                      return globalThis.navigator.share(
                                        shareData
                                      );
                                    })();
                                  }
                                };
                                return (({ customFunction }) => {
                                  return customFunction();
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["runCode"] != null &&
                            typeof $steps["runCode"] === "object" &&
                            typeof $steps["runCode"].then === "function"
                          ) {
                            $steps["runCode"] = await $steps["runCode"];
                          }
                        }}
                        size={"compact"}
                      />

                      <Button
                        children2={
                          "\u0628\u0627\u0632\u06af\u0634\u062a \u0628\u0647 \u067e\u0630\u06cc\u0631\u063424"
                        }
                        className={classNames(
                          "__wab_instance",
                          sty.button___45H5S
                        )}
                        isDisabled={(() => {
                          try {
                            return $state.waiting;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return [];
                            }
                            throw e;
                          }
                        })()}
                        onClick={async event => {
                          const $steps = {};

                          $steps["updateWaiting"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["waiting"]
                                  },
                                  operation: 0,
                                  value: true
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateWaiting"] != null &&
                            typeof $steps["updateWaiting"] === "object" &&
                            typeof $steps["updateWaiting"].then === "function"
                          ) {
                            $steps["updateWaiting"] =
                              await $steps["updateWaiting"];
                          }

                          $steps["updateWaiting3"] = true
                            ? (() => {
                                const actionArgs = {
                                  args: ["https://www.paziresh24.com/"]
                                };
                                return $globalActions[
                                  "Hamdast.openLink"
                                ]?.apply(null, [...actionArgs.args]);
                              })()
                            : undefined;
                          if (
                            $steps["updateWaiting3"] != null &&
                            typeof $steps["updateWaiting3"] === "object" &&
                            typeof $steps["updateWaiting3"].then === "function"
                          ) {
                            $steps["updateWaiting3"] =
                              await $steps["updateWaiting3"];
                          }
                        }}
                        outline={true}
                        size={"compact"}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(() => {
            try {
              return $ctx.query.type == "logo";
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <section className={classNames(projectcss.all, sty.section__zwP9V)}>
              {(() => {
                try {
                  return true;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <div className={classNames(projectcss.all, sty.freeBox__csEvg)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__imbei)}
                  >
                    {(() => {
                      try {
                        return $state.waiting;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return true;
                        }
                        throw e;
                      }
                    })() ? (
                      <Icon2Icon
                        className={classNames(projectcss.all, sty.svg__clk1D)}
                        role={"img"}
                      />
                    ) : null}
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__uR2F)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/image42.svg",
                        fullWidth: 102.473,
                        fullHeight: 108.85,
                        aspectRatio: 0.941415
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__yYZjY)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/bluPaySvg.svg",
                        fullWidth: 48,
                        fullHeight: 48,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__t9QVd)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/sepSvg.svg",
                        fullWidth: 32,
                        fullHeight: 32,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__aOO8)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/visaSvg.svg",
                        fullWidth: 24,
                        fullHeight: 18,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__kWcMs)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/mastercardSvg.svg",
                        fullWidth: 24,
                        fullHeight: 18,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__icBr3)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/creditcardSvg.svg",
                        fullWidth: 30,
                        fullHeight: 30,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__zhx4C)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/amexSvg.svg",
                        fullWidth: 24,
                        fullHeight: 18,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__kgVd)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/paybybankSvg.svg",
                        fullWidth: 30,
                        fullHeight: 30,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__tnt9L)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/banktransferSvg.svg",
                        fullWidth: 30,
                        fullHeight: 30,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__mqh8Q)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/linkSvg.svg",
                        fullWidth: 225,
                        fullHeight: 225,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__hb9Yc)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/linkIco.ico",
                        fullWidth: 256,
                        fullHeight: 256,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__wqU3W)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/link2Svg.svg",
                        fullWidth: 24,
                        fullHeight: 24,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___4BTrh)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/stripeWebp.webp",
                        fullWidth: 256,
                        fullHeight: 256,
                        aspectRatio: undefined
                      }}
                    />

                    <VisamasterSvgIcon
                      className={classNames(projectcss.all, sty.svg__mFawF)}
                      role={"img"}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__iuNnk)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/visamasterPng2.png",
                        fullWidth: 593,
                        fullHeight: 153,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___1Hhs9)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/visamastercardPng.png",
                        fullWidth: 300,
                        fullHeight: 298,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__qzkBg)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/katibe/images/walletPng2.png",
                        fullWidth: 50,
                        fullHeight: 50,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
              ) : null}
            </section>
          ) : null}
          <SideEffect
            data-plasmic-name={"sideeffectPageload"}
            data-plasmic-override={overrides.sideeffectPageload}
            className={classNames("__wab_instance", sty.sideeffectPageload)}
            deps={(() => {
              try {
                return [$ctx.query.userid];
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
            onMount={async () => {
              const $steps = {};

              $steps["getUsers"] =
                $ctx.query.userid != undefined && $ctx.query.userid > 0
                  ? (() => {
                      const actionArgs = {
                        args: [
                          undefined,
                          (() => {
                            try {
                              return (
                                "https://apigw.paziresh24.com/v1/users/" +
                                $ctx.query.userid
                              );
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                        ]
                      };
                      return $globalActions["Fragment.apiRequest"]?.apply(
                        null,
                        [...actionArgs.args]
                      );
                    })()
                  : undefined;
              if (
                $steps["getUsers"] != null &&
                typeof $steps["getUsers"] === "object" &&
                typeof $steps["getUsers"].then === "function"
              ) {
                $steps["getUsers"] = await $steps["getUsers"];
              }

              $steps["updateUser"] =
                $ctx.query.userid != undefined &&
                $ctx.query.userid > 0 &&
                $steps.getUsers.status == 200
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["user"]
                        },
                        operation: 0,
                        value: $steps.getUsers.data
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
              if (
                $steps["updateUser"] != null &&
                typeof $steps["updateUser"] === "object" &&
                typeof $steps["updateUser"].then === "function"
              ) {
                $steps["updateUser"] = await $steps["updateUser"];
              }

              $steps["updateWaiting"] = false
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["waiting"]
                      },
                      operation: 0,
                      value: true
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateWaiting"] != null &&
                typeof $steps["updateWaiting"] === "object" &&
                typeof $steps["updateWaiting"].then === "function"
              ) {
                $steps["updateWaiting"] = await $steps["updateWaiting"];
              }

              $steps["updateWaiting2"] = false
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["waiting"]
                      },
                      operation: 0,
                      value: false
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateWaiting2"] != null &&
                typeof $steps["updateWaiting2"] === "object" &&
                typeof $steps["updateWaiting2"].then === "function"
              ) {
                $steps["updateWaiting2"] = await $steps["updateWaiting2"];
              }
            }}
          />

          <SideEffect
            data-plasmic-name={"onLoad"}
            data-plasmic-override={overrides.onLoad}
            className={classNames("__wab_instance", sty.onLoad)}
            onMount={async () => {
              const $steps = {};

              $steps["invokeGlobalAction"] = true
                ? (() => {
                    const actionArgs = {
                      args: [
                        undefined,
                        "https://apigw.paziresh24.com/katibe/v1/ip-location"
                      ]
                    };
                    return $globalActions["Fragment.apiRequest"]?.apply(null, [
                      ...actionArgs.args
                    ]);
                  })()
                : undefined;
              if (
                $steps["invokeGlobalAction"] != null &&
                typeof $steps["invokeGlobalAction"] === "object" &&
                typeof $steps["invokeGlobalAction"].then === "function"
              ) {
                $steps["invokeGlobalAction"] =
                  await $steps["invokeGlobalAction"];
              }

              $steps["updateIplocation"] =
                $steps.invokeGlobalAction.status == 200
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["iplocation"]
                        },
                        operation: 0,
                        value: $steps.invokeGlobalAction.data
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
              if (
                $steps["updateIplocation"] != null &&
                typeof $steps["updateIplocation"] === "object" &&
                typeof $steps["updateIplocation"].then === "function"
              ) {
                $steps["updateIplocation"] = await $steps["updateIplocation"];
              }
            }}
          />

          <Embed
            data-plasmic-name={"embedHtml"}
            data-plasmic-override={overrides.embedHtml}
            className={classNames("__wab_instance", sty.embedHtml)}
            code={
              '<script type="text/javascript">\r\n    (function(c,l,a,r,i,t,y){\r\n        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};\r\n        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;\r\n        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);\r\n    })(window, document, "clarity", "script", "rr61es0fkb");\r\n</script>'
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "txtAmount", "sideeffectPageload", "onLoad", "embedHtml"],
  txtAmount: ["txtAmount"],
  sideeffectPageload: ["sideeffectPageload"],
  onLoad: ["onLoad"],
  embedHtml: ["embedHtml"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  txtAmount: typeof TextInput;
  sideeffectPageload: typeof SideEffect;
  onLoad: typeof SideEffect;
  embedHtml: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCharge__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCharge__VariantsArgs;
    args?: PlasmicCharge__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCharge__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCharge__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCharge__ArgProps,
          internalVariantPropNames: PlasmicCharge__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCharge__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCharge";
  } else {
    func.displayName = `PlasmicCharge.${nodeName}`;
  }
  return func;
}

export const PlasmicCharge = Object.assign(
  // Top-level PlasmicCharge renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    txtAmount: makeNodeComponent("txtAmount"),
    sideeffectPageload: makeNodeComponent("sideeffectPageload"),
    onLoad: makeNodeComponent("onLoad"),
    embedHtml: makeNodeComponent("embedHtml"),

    // Metadata about props expected for PlasmicCharge
    internalVariantProps: PlasmicCharge__VariantProps,
    internalArgProps: PlasmicCharge__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "شارژ کیف پول",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCharge;
/* prettier-ignore-end */
